### ISSUE TITLE
Some Toolbar icons are not centered

### ISSUE THREAD

**Issue by pouyakary** [microsoft/vscode-codicons#139]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.0
- OS Version: 12.5.1

These two icons are not centered in the toolbar. This occurs everywhere:

<img width="512" alt="Screen Shot 2022-10-10 at 4 52 50 PM" src="https://user-images.githubusercontent.com/2157285/194878251-49b39c04-a699-49fe-9be0-2aeec8d71eee.png">

<img width="512" alt="Screen Shot 2022-10-10 at 4 53 18 PM" src="https://user-images.githubusercontent.com/2157285/194878277-060cd995-6c37-4091-8312-8b9a44f1ec84.png">

**Comment by daviddossett** [comment]
Here's the basic problem. Codicons are built on an even pixel grid, which makes things challenging when you introduce elements that are supposed to sit directly in the middle.

Current icon, offset by design to account for this:

<img width="1057" alt="CleanShot 2023-05-01 at 15 35 06@2x" src="https://user-images.githubusercontent.com/25163139/235543299-100eb1ff-aefd-4c43-a85a-84e10b8f7078.png">

Here's how this looks if the container is perfectly even—you can't center the divider

<img width="1134" alt="CleanShot 2023-05-01 at 15 35 14@2x" src="https://user-images.githubusercontent.com/25163139/235543453-d8c4c071-7326-4774-a3a3-17cc7fdc2109.png">

I may consider changing this icon anyway, but wanted to share the immediate challenge that I saw.

**Comment by pouyakary** [comment]
Every time I mistake padding and then arrive at this problem :) damn evens :))

**Comment by hbons** [comment]
Tracking in #243
