### ISSUE TITLE
icon request: zsh

### ISSUE THREAD

**Issue by guppy0130** [microsoft/vscode-codicons#157]
**Is your icon request related to a problem? Please describe.**
No particular problem, just thought it would be neat to see the zsh logo when opening a zsh shell in vscode :)

**Describe the solution you'd like**
Adding the zsh icons from [their (official?) repo](https://github.com/Zsh-art/logo)

Noticed that in #68 it was requested to have the svg, so I think https://github.com/Zsh-art/logo/blob/main/svg/white_vertical_icon.svg?short_path=c7a2046 would be sufficient? The only potential issue I see with this is that I see your other icons use `fill="currentColor"` (assuming for coloring in different usage scenarios?) while they have hardcoded stroke colors.

**Describe alternatives you've considered**

* Using the default `terminal` icon (current behavior), which is fine, but the zsh icon would be more specific
* `terminal-linux` is also ok, but again, could be more specific
* `terminal-{bash,ubuntu,debian,tmux}` aren't correct

**Additional context**
N/A

**Comment by hbons** [comment]
Since zsh is the default shell on macOS, I don't think we should do this (at least on that platform). Right now we use the default `terminal` icon for that:

<img width="242" alt="image" src="https://github.com/microsoft/vscode-codicons/assets/103326/bceb7514-9ae8-43bf-8181-9adf0adda773">

Using the `%_` could be confusing for new users.
