### ISSUE TITLE
How should this actually be built?

### ISSUE THREAD

**Issue by piersdeseilligny** [microsoft/vscode-codicons#16]
I'm trying to build this with some additional icons for my vscode extension (for use in a webview). However, I can't seem to manage to build it. After running `npm install`,  `npm run build` isn't working, as there isn't actually a script in package.json called "build". I tried `npm run fonts` instead, but it's throwing an error internal to webfonts-generator (`TypeError: Cannot read property 'deps' of undefined`).

How should I actually build this? My OS is Windows 10 19041.

**Comment by misolori** [comment]
Sorry about that, there's a couple of unix scripts that are used for moving/cleaning up files so it's not currently possible to build on Windows, I'll see if I can setup a Docker container for this. The default build task `dev` should be the one to build this locally.

**Comment by misolori** [comment]
I've converted the scripts so that you can build this on Windows. I ran into issues on my Windows machine that I believe are related to one of the dependency packages on Windows. So I also added a Docker container that can be used with the VS Code [Containers extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) so that you don't run into these issues.

Let me know if this helps you build this locally via `npm run build`.
