### ISSUE TITLE
[New Icon Request] Add new icon for "export"

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-codicons#19]
In our extension, we have an action called `Export Jar`, which generates a build file to the user.

Can we add a new icon for this kind of action?

**Comment by akaroml** [comment]
I think an icon with the meaning "Export" is a general thing that could be used by other extensions too.

**Comment by misolori** [comment]
@jdneo @akaroml would this icon below work?

![image](https://user-images.githubusercontent.com/35271042/92525074-078afa80-f1d8-11ea-872c-ee0cb79e327c.png)

**Comment by akaroml** [comment]
Thank you for that @misolori 

This is way proper than what we have right now. I really like the pointer concept, which suggests the action.

Just an extra thought of making the "boundary" concept more obvious. This is because the action "export" is to move something from A to B, so it would be great to visualize the boundary between A and B. I'm guessing the vertical line stands for the boundary, but I'm not so sure. And that's why I'm thinking whether we could do a bit more with that concept.

**Comment by misolori** [comment]
Yea typically export has a starting point and then an arrow, here's what comes up when you do an icon search for export:

![image](https://user-images.githubusercontent.com/35271042/92615712-41104400-f272-11ea-8595-3ef772841e88.png)

We already have the following icons:

![image](https://user-images.githubusercontent.com/35271042/92615768-52f1e700-f272-11ea-9ea5-67b0333b5d5d.png)

![image](https://user-images.githubusercontent.com/35271042/92615808-5e451280-f272-11ea-80b6-70c325c9e937.png)


So I'd be worried to make this too similar to those. Also, the one from above is the same one used in the Microsoft Design Language. I can add this one to codicons and then we can gauge the feedback.

**Comment by misolori** [comment]
Fixed via https://github.com/microsoft/vscode-codicons/commit/5bcb1a045413eb5a9737e6e46411e13f9c4e5c9c

**Comment by jdneo** [comment]
Thank you @misolori !

**Comment by akaroml** [comment]
@misolori It makes total sense. We'll use the icon in the next release. Thank you.
