### ISSUE TITLE
Request for a debug-all action

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-codicons#72]
I'm looking for a "debug all" action, using the double arrows of "run-all" with the addition of the 🐛as seen in the `debug-alt` icon

**Comment by misolori** [comment]
Wondering if it might be "too much" icon:

<img width="646" alt="CleanShot 2021-07-14 at 10 23 43@2x" src="https://user-images.githubusercontent.com/35271042/125665446-738a830e-590e-4ff8-a00d-900e6fb4eac9.png">

and at 100%:

<img width="105" alt="CleanShot 2021-07-14 at 10 21 06@2x" src="https://user-images.githubusercontent.com/35271042/125665415-cdf33200-cb6f-4c56-bc20-0ff218e60f73.png">

Let me know what you think

**Comment by connor4312** [comment]
Hm, yea. We still want the "run all" action for gutters that distinguishes groups versus single tests, but perhaps in the menu bar we should use the single version and therefore don't need a "debug all" icon there... Though something useful would be alt-clicking on gutter decorations to debug tests, and having a debug all icon there would be useful, since you already seem to have made it 😛

**Comment by misolori** [comment]
I like the alt-click, we do that with splitting editors, though not highly discoverable. Though there will be a bit of a shift when doing this as the icons aren't positioned at the same place. 

<img width="719" alt="CleanShot 2021-07-14 at 11 27 52@2x" src="https://user-images.githubusercontent.com/35271042/125673651-74cea01b-ef98-4d5a-9f43-a544aead8843.png">

I intentionally moved it to the right to show more of the icon otherwise it looked a little odd:

<img width="173" alt="CleanShot 2021-07-14 at 11 29 29@2x" src="https://user-images.githubusercontent.com/35271042/125673828-54b4affd-253d-4354-a6b6-3a2df538936e.png">

**Comment by connor4312** [comment]
Yea, it's somewhat subtle but a useful behavior for people who test frequently and tend to use their mouse.

I think the slightly shift is okay 🙂

**Comment by misolori** [comment]
Ok cool, i'll add this one then. thanks for the quick feedback!

**Comment by misolori** [comment]
<img width="162" alt="CleanShot 2021-07-15 at 16 21 03@2x" src="https://user-images.githubusercontent.com/35271042/125869697-2e7be30e-d3c0-475d-a1f1-ac7cd8dfb5e3.png">
