### ISSUE TITLE
Can't set icons in windows terminal

### ISSUE THREAD

**Issue by bryant-the-coder** [microsoft/vscode-codicons#97]
**Describe the bug**
It breaks the entire terminal

**To Reproduce**
1. Download the font
2. Set it in windows terminal
3. See error

**Expected behavior**
Entire terminal breaks. Whenever i reopen the terminal, it will auto clpse

**Environment**
 - OS: Windows

**Comment by misolori** [comment]
@bryant-the-coder  screenshot please, these icons were not designed to work in terminals.

**Comment by bryant-the-coder** [comment]
> @bryant-the-coder  screenshot please, these icons were not designed to work in terminals.

@misolori heyy, there is no scrrenshot. It is because the terminal will suddenly hang and close automatically. When i wanna reopen it, it automatically close again

**Comment by bryant-the-coder** [comment]
but y some other terminal like alacritty, kitty and a few to br named. they can set this font. ಥ‿ಥ

**Comment by misolori** [comment]
![image](https://user-images.githubusercontent.com/35271042/151914407-4f042e2a-33ec-4eb0-a53f-cad21dd1e6a8.png)

Setting codicons as your primary font is not supported nor recommended since it only includes glyphs and not text (which is why you have to check "show all". Thanks for reporting this issue but will close this as it's not supported, not sure why it works in some terminals, you might create an issue on the windows terminal repo.
